[project]
name = "crazyflie-client"
version = "0.1.0"
description = "Crazyflie client and analysis environment for AE483"
requires-python = "==3.12.*"
dependencies = [
    "numpy",
    "scipy",
    "sympy",
    "matplotlib",
    "jupyter",
    "cflib",
    "cfclient",
    "qtm-rt",
]

[tool.uv]
managed = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = [
    "ae483clients.py",
    "ae483tools.py"
]