"""Functions that we provide.

Students do not edit this file — that is what mytools.py is for.

Maintainer note: never import from ae483.mytools here. The dependency runs one
way (mytools imports tools, not the reverse). A cycle would not fail loudly —
a star import from a partially initialized module silently binds only the names
defined so far, and surfaces later as a confusing NameError.
"""

import json
import numpy as np
from pathlib import Path
from scipy.spatial.transform import Rotation
import matplotlib.pyplot as plt


def load_hardware_data(filename):
    with open(Path(filename), 'r') as f:
        data = json.load(f)
        return data['drone'], data['mocap'], data['bodies']


def gains_as_text(gains, decimals=4):
    """
    Format control gains compactly, one line per input, in the same order they
    appear in the equations of your controller.
    """
    # Work out the labels and column widths first, so that every line lines up.
    # Each gain is named k_<input>_<state>, and the name of the input is known
    # from the eq_<input> entry that comes just before its gains - so there is
    # no need to guess where the name of the input ends and the state begins.
    labels = {}
    name_of_input = None
    for name in gains:
        if name.startswith('eq_'):
            name_of_input = name[len('eq_'):]
            labels[name] = 'eq'
        else:
            prefix = f'k_{name_of_input}_'
            labels[name] = name[len(prefix):] if name.startswith(prefix) else name
    label_width = max(len(x) for x in labels.values())
    input_width = max(len(n[len('eq_'):]) for n in gains if n.startswith('eq_'))

    lines, parts, name_of_input = [], [], None
    for name, value in gains.items():
        if name.startswith('eq_'):
            if name_of_input is not None:
                lines.append(f'{name_of_input:>{input_width}s}:  ' + '  '.join(parts))
            name_of_input = name[len('eq_'):]
            parts = []
        parts.append(f'{labels[name]:>{label_width}s} {value:{decimals + 4}.{decimals}f}')
    if name_of_input is not None:
        lines.append(f'{name_of_input:>{input_width}s}:  ' + '  '.join(parts))
    return '\n'.join(lines)


def show_gains(filename, decimals=4):
    """
    Print the control gains that were used for a flight.
    """
    with open(Path(filename), 'r') as f:
        data = json.load(f)
    gains = data.get('gains', None)
    created = data.get('gains_created', None)

    if gains:
        print(f'Control gains, designed {created}:' if created else 'Control gains:')
        print(gains_as_text(gains, decimals=decimals))
    elif data.get('use_controller', False):
        print('WARNING: This flight was set up to use your controller, but no gains')
        print('were recorded. That means the gains never reached the drone, so it')
        print('would not have flown. Check the output of flight.py for an error.')
    else:
        print('This flight used the default controller, so there were no gains.')


def check_mocap_coverage(filename):
    # Load data
    raw_data_drone, raw_data_mocap, raw_data_bodies = load_hardware_data(filename)

    # Compute statistics
    how_many_timesteps = len(raw_data_mocap['z'])
    how_many_dropouts = len(np.argwhere(np.isnan(raw_data_mocap['z'])).flatten())
    percent_coverage = 100. * (1. - (how_many_dropouts / how_many_timesteps))
    elapsed_time = raw_data_mocap['time'][-1] - raw_data_mocap['time'][0]
    sample_rate = how_many_timesteps / elapsed_time

    # Plot data (with relevant statistics in the title)
    fig, ax = plt.subplots(1, 1, figsize=(7, 3), tight_layout=True)
    ax.plot(raw_data_mocap['time'], raw_data_mocap['z'])
    ax.set_xlabel('t (seconds)')
    ax.set_ylabel('z (meters)')
    ax.set_ylim(0., 1.)
    ax.set_title(f'({filename}) Tracked {percent_coverage:.1f}% of {how_many_timesteps} time steps at about {sample_rate:.0f} Hz')
    ax.grid()    


def resample_data_drone(raw_data, hz=1e2, t_min_offset=0., t_max_offset=0.):
    # Copy data (FIXME: may be unnecessary?)
    data = {}
    for key, val in raw_data.items():
        data[key] = {
            'time': val['time'].copy(),
            'data': val['data'].copy(),
        }

    # Convert lists to numpy arrays
    for key, val in data.items():
        val['data'] = np.array(val['data'], dtype=np.float64).copy()
        val['time'] = np.array(val['time'], dtype=np.float64).copy()

    # Find time interval
    t_min = -np.inf
    t_max = np.inf
    for key, val in data.items():
        t_min = max(t_min, val['time'][0])
        t_max = min(t_max, val['time'][-1])
    if (t_min_offset < 0) or (t_min_offset > t_max - t_min):
        raise Exception(f't_min_offset = {t_min_offset:.4f} must be in [0, {t_max - t_min:.4f}]')
    if (t_max_offset < 0) or (t_max_offset > t_max - t_min):
        raise Exception(f't_max_offset = {t_max_offset:.4f} must be in [0, {t_max - t_min:.4f}]')
    t_min += t_min_offset
    t_max -= t_max_offset

    # Find zero time
    t_zero = t_min

    # Do time shift
    t_min -= t_zero
    t_max -= t_zero
    for key, val in data.items():
        val['time'] -= t_zero

    # Create an array of times at which to subsample
    if np.round(hz) != hz:
        raise Exception(f'hz = {hz} must be an integer')
    nt = int(1 + np.floor((t_max - t_min) * hz))
    t = t_min + np.arange(0, nt) / hz
    
    # Resample raw data with linear interpolation
    resampled_data = {'time': t}
    for key, val in data.items():
        resampled_data[key] = np.interp(t, val['time'], val['data'])
        
    # Return the resampled data
    return resampled_data


def resample_data_mocap(raw_data, t, t_shift=0., t_min_offset=0.):
    # Copy data (FIXME: may be unnecessary?) and convert lists to numpy arrays
    data = {}
    for key, val in raw_data.items():
        data[key] = np.array(val, dtype=np.float64).copy()
    
    # Find nan
    is_valid = np.ones_like(data['time']).astype('bool')
    for val in data.values():
        is_valid = np.bitwise_and(is_valid, ~np.isnan(val))
    i_is_valid = np.argwhere(is_valid).flatten()

    # Remove nan
    for key, val in data.items():
        data[key] = val[i_is_valid]
    
    # Do time offset
    t_min = data['time'][0]
    t_max = data['time'][-1]
    if (t_min_offset < 0.) or (t_min_offset > t_max - t_min):
        raise Exception(f't_min_offset = {t_min_offset:.4f} must be in [0, {t_max - t_min:.4f}]')
    i_min = np.argwhere(data['time'] - t_min >= t_min_offset).flatten()
    if len(i_min) == 0:
        raise Exception(f't_min_offset = {t_min_offset:.4f} leaves no data (choose a smaller value)')
    i_min = i_min[0]
    for key, val in data.items():
        data[key] = val[i_min:]
    
    # Do time shift
    data['time'] -= (data['time'][0] - t_shift)

    # Resample raw data with linear interpolation
    resampled_data = {'time': t.copy()}
    for key, val in data.items():
        if key != 'time':
            resampled_data[key] = np.interp(t, data['time'], val)
    
    # Return the resampled data
    return resampled_data


def only_in_flight(data_drone, data_mocap=None, t_interval=None):
    # Verify the desired z position was logged
    if ('ae483log.p_z_des' not in data_drone.keys()) and ('ctrltarget.z' not in data_drone.keys()):
        raise Exception('Neither "ae483log.p_z_des" or "ctrltarget.z" were logged.')
    
    # Find the indices at which the desired z position was positive
    i = []
    for k in ['ae483log.p_z_des', 'ctrltarget.z']:
        if k in data_drone.keys():
            j = np.argwhere(data_drone[k] > 0).flatten()
            if len(j) > len(i):
                i = j
    
    # Verify that there were indices at which the desired z position was positive
    if len(i) < 2:
        raise Exception('The desired z position was never positive.')
    
    # Get first and last index at which the desired z position was positive
    i_first = i[0]
    i_last = i[-1]

    # Adjust the first and last index, if desired, to get a subset of data with
    # a given length centered in the middle of the flight time (if desired)
    if t_interval is not None:
        # Get time step (assuming it is constant)
        dt = data_drone['time'][1] - data_drone['time'][0]

        # Get number of time steps that would correspond to desired time interval
        n_interval = int(np.ceil(t_interval / dt))
        n_flight = (i_last + 1) - i_first
        
        # Verify that we have at least that number of time steps
        if n_flight < n_interval:
            t_flight = n_flight * dt
            raise Exception(f'The requested time interval ({t_interval:.2f} s) is longer than the flight time ({t_flight:.2f} s).')
        
        # Get first and last index again
        i_first += int(np.floor((n_flight - n_interval) / 2))
        i_last = i_first + n_interval

    # Truncate and time-shift data_drone
    for k in data_drone.keys():
        data_drone[k] = data_drone[k][i_first:(i_last + 1)]
    data_drone['time'] -= data_drone['time'][0]
    
    # Truncate and time-shift data_mocap, if it exists
    if data_mocap is not None:
        # Verify mocap data actually exist
        if len(data_mocap.keys()) == 0:
            raise Exception('The dictionary "data_mocap" is empty.')

        # Truncate mocap data
        for k in data_mocap.keys():
            data_mocap[k] = data_mocap[k][i_first:(i_last + 1)]

        # Time-shift mocap data
        data_mocap['time'] -= data_mocap['time'][0]

        # Verify drone and mocap data are the same
        assert(np.allclose(data_drone['time'], data_mocap['time']))
